function [Hd, b] = psr_makeFIRfilter_300to12500Hz
%TESTFILTER_300TO12500HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 06-Dec-2024 11:48:46

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 30000;  % Sampling Frequency

Fstop1 = 200;             % First Stopband Frequency
Fpass1 = 300;             % First Passband Frequency
Fpass2 = 12500;           % Second Passband Frequency
Fstop2 = 12600;           % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
